### ISSUE TITLE
fix the bugs  in the PyG library

### ISSUE THREAD

**Issue by yyt1466028622** [QwQ2000/TheWebConf24-LTGNN-PyTorch#1]
Hi,I hope this message finds you well. I recently came across your repository associated with the paper you published. However, while running the code, I noticed your alert Caution: Use pyg-lib for sampling acceleration here. May need to fix the bugs in the PyG library (neighbor_sampler.py). How should I modify neighbor_sampler.py in the PyG library?

**Comment by QwQ2000** [comment]
Thank you for your interest in our work! 🤗 

I’ve reviewed the source code for the `torch_geometric.sampler.NeighborSampler` class, and I believe I’ve identified a bug that affects the functionality of `torch_geometric.loader.NeighborLoader`, which is crucial for neighbor sampling in LTGNN. To fix this bug, please refer to the source code of `torch_geometric.sampler.NeighborSampler`, and make a slight modification at around **line 299** in the `_sample` method.

Here’s the original line of code:
```python
row, col, node, edge, batch, _ = out + (None, )
```
And here’s the revised version:
```python
# *** Caution: changed the PyG code here!
row, col, node, edge, batch, _ = out #+ (None, )
```
This change should address the issue and allow the LTGNN code to work correctly. There is **no need** to re-compile or re-install any Python libraries after applying this revision. You can simply execute the LTGNN code, and everything will be fine. 

However, please be cautious. Depending on the version of the PyG library you’re working with, you may not always need this exact revision. I’ve only tested this code with PyG versions `torch_geometric==2.2.0, 2.3.1` and pyg-lib version `pyg-lib==0.2.0+pt113cu117`. If you find the proposed modification is incorrect in your own context, I kindly recommend either aligning your PyG version with mine or promptly reporting any encountered errors during code execution. Besides, If you find that the LTGNN code operates correctly without implementing this revision, feel free to proceed and just allow the code to execute.
